const USER = {
  UPDATE_FIELD: 'USER_UPDATE_FIELD',
  SUCCESS: 'USER_SUCCESS',
  FAIL: 'USER_FAIL',
  UPDATE_PROFILE: 'USER_UPDATE_PROFILE',
  CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD',
  LOCATION_SERVICE: 'USER_LOCATION_SERVICE',
  LOAD_SAVED_LIST: 'USER_LOAD_SAVED_LIST',
  SAVE_BUSINESS: 'USER_SAVE_BUSINESS',
  UNSAVE_BUSINESS: 'USER_UNSAVE_BUSINESS'
};

const AUTH = {
  UPDATE_FIELD: 'AUTH_UPDATE_FIELD',
  UPDATE_IMAGES: 'AUTH_UPDATE_IMAGES',
  UPDATE_REGIONS: 'AUTH_UPDATE_REGIONS',
  LOGIN: 'AUTH_LOGIN',
  LOGOUT: 'AUTH_LOGOUT',
  SUCCESS: 'AUTH_SUCCESS',
  FAIL: 'AUTH_FAIL',
  CHANGE_PASSWORD: 'AUTH_CHANGE_PASSWORD',
  CHANGE_PASSWORD_CONFIRM: 'AUTH_CHANGE_PASSWORD_CONFIRM',
  DELETE_IMAGE: 'AUTH_DELETE_IMAGE'
}

const LOADING = {
  ENABLE: 'LOADING_ENABLE',
  DISABLE: 'LOADING_DISABLE'
}

const SEARCH = {
  UPDATE_FIELD: 'SEARCH_UPDATE_FIELD',
  ENABLE: 'SEARCH_ENABLE',
  DISABLE: 'SEARCH_DISABLE'
}

const BUSINESS = {
  LOAD_IMAGES: 'BUSINESS_LOAD_IMAGES',
  UPDATE_FIELD: 'BUSINESS_UPDATE_FIELD',
  UPDATE_IMAGES: 'BUSINESS_UPDATE_IMAGES',
  UPDATE_REGIONS: 'BUSINESS_UPDATE_REGIONS',
  DELETE_IMAGE: 'BUSINESS_DELETE_IMAGE',
  FAIL: 'BUSINESS_FAIL',
  SUCCESS: 'BUSINESS_SUCCESS',
  LOAD_LIST: 'BUSINESS_LOAD_LIST',
  ADD: 'BUSINESS_ADD',
  ADD_RATING: 'BUSINESS_ADD_RATING',
  UPDATE: 'BUSINESS_UPDATE',
  CLEAR: 'BUSINESS_CLEAR',
  REMOVE: 'BUSINESS_REMOVE',
  UPDATE_CURRENT_LOCATION: 'BUSINESS_UPDATE_CURRENT_LOCATION',
  UPDATE_LOCATION: 'BUSINESS_UPDATE_LOCATION'
}

const REVIEW = {
  SUCCESS: 'REVIEW_SUCCESS',
  FAIL: 'REVIEW_FAIL',
  UPDATE_FIELD: 'REVIEW_UPDATE_FIELD',
  CLEAR: 'REVIEW_CLEAR'
}

export { 
  USER,
  AUTH,
  LOADING,
  SEARCH,
  BUSINESS,
  REVIEW
};